### ISSUE TITLE
Android 下PivotItem的Header不显示内容

### ISSUE THREAD

**Issue by HaoLife** [unoplatform/Uno.QuickStart#13]
在Android下，PivotItem的Header不显示问题
![image](https://user-images.githubusercontent.com/25171162/41160609-d70310da-6b62-11e8-9e6f-5fc35d1bc474.png)

https://stackoverflow.com/questions/31641979/using-tablayout-inside-a-fragment-tab-text-invisible

**Comment by ghuntley** [comment]
Howdy @HaoLife. If I understand correctly "Under Android, PivotItem Header does not display problems" is that right? What version are you using? As this issue is quite old I'm going to close this out. If you can reproduce from the latest published version from NuGet.org please raise a bug/feature request at https://github.com/nventive/Uno
