### ISSUE TITLE
Stretch UniformToFill doesn't work in the same way for UWP or Android

### ISSUE THREAD

**Issue by samoteph** [unoplatform/Uno.QuickStart#4]
On UWP an image with Stretch attribut set to UniformToFill draw a stretched but aligned to left image. It's a normal (but weird) behavior with XAML. On Android the image is centered.
On UWP the tricks to center the image is to contain the image on a grid and set the HorizontalAlignment/VerticalAlignment attribute of the image to Center. Unfortunatly the tricks on Android  doesn't work :/

**Comment by jeromelaban** [comment]
This should have been fixed since then. If you find a similar issue, please open a new issue here: https://github.com/unoplatform/uno/issues/new/choose

<blockquote><img src="https://github.githubassets.com/images/modules/open_graph/github-logo.png" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com">Build software better, together</a></strong></div><div>GitHub is where people build software. More than 40 million people use GitHub to discover, fork, and contribute to over 100 million projects.</div></blockquote>
